name: build-pygmo
run-name: ${{ github.actor }} - test setup for building pygmo
env:
  prefix: "${{ github.workspace }}/libs"
  TBB_ROOT: "${{ github.workspace }}/libs"
  Eigen3_DIR: "${{ github.workspace }}/libs"
  NLopt_DIR: "${{ github.workspace }}/libs"
  CMAKE_LIBRARY_PATH: "${{ github.workspace }}"

on: [push]
jobs:
  test:
    runs-on: windows-2022
    steps:
      - run: echo ${{ env.prefix }}
        shell: powershell
      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.0.2
      - name: Install boost
        uses: MarkusJx/install-boost@v2.4.5
        id: install-boost
        with:
            # REQUIRED: Specify the required boost version
            # A list of supported versions can be found here:
            # https://github.com/MarkusJx/prebuilt-boost/blob/main/versions-manifest.json
            boost_version: 1.84.0
            # OPTIONAL: Specify a custon install location
            # boost_install_dir: C:\
            # OPTIONAL: Specify a platform version
            platform_version: 2022
            # OPTIONAL: Specify a toolset
            toolset: msvc

            # NOTE: If a boost version matching all requirements cannot be found,
            # this build step will fail
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12.4' 
      # - name: setup cmake
        # uses: lukka/get-cmake@latest
      # - name: run-vcpkg
        # uses: lukka/run-vcpkg@v11.5
      # - run: vcpkg install pagmo2

      - uses: actions/checkout@v4

      - name: Cache TBB
        id: cache-tbb
        uses: actions/cache@v4
        with:
          path: oneTBB
          key: tbb-cache

      - name: Build TBB
        if: steps.cache-tbb.outputs.cache-hit != 'true'
        run: .\buildtbb.ps1
        shell: powershell

      - run: cmake --install ./oneTBB/build --prefix ${{ env.prefix }}
        shell: powershell

      - name: Cache nlopt
        id: cache-nlopt
        uses: actions/cache@v4
        with:
          path: nlopt
          key: nlopt-cache

      - name: Get nlopt
        if: steps.cache-nlopt.outputs.cache-hit != 'true'
        run: .\buildnlopt.ps1
        shell: powershell

      - run: cmake --install ./nlopt/build --prefix ${{ env.prefix }}

      # - name: Install ipopt
        # run: ./extract-ipopt.ps1
        # shell: powershell

      - name: Install Eigen3
        uses: kupns-aka-kupa/setup-eigen3@master
        with:
          version: 3.4.0
        env:
          CMAKE_GENERATOR: "Visual Studio 17 2022"

      - name: Cache pagmo
        id: cache-pagmo
        uses: actions/cache@v4
        with:
          path: pagmo2
          key: pagmo-cache

      - name: Build pagmo
        if: steps.cache-pagmo.outputs.cache-hit != 'true'
        run: .\buildpagmo.ps1
        shell: powershell

      - run: cmake --version
      - run: echo Hello world!
