name: learn-github-actions
run-name: ${{ github.actor }} is learning GitHub Actions
on: [push]
jobs:
  test:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.0.2
      - name: Install boost
        uses: MarkusJx/install-boost@v2.4.5
        id: install-boost
        with:
            # REQUIRED: Specify the required boost version
            # A list of supported versions can be found here:
            # https://github.com/MarkusJx/prebuilt-boost/blob/main/versions-manifest.json
            boost_version: 1.84.0
            # OPTIONAL: Specify a custon install location
            boost_install_dir: C:\boost
            # OPTIONAL: Specify a platform version
            platform_version: 2022
            # OPTIONAL: Specify a toolset
            toolset: msvc

            # NOTE: If a boost version matching all requirements cannot be found,
            # this build step will fail
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12.4' 
      - run: echo Hello world!
